### PR TITLE
Some adjustments regarding future themeing, really remove use_mobile_view config

### PR DESCRIPTION
**Pull request by andi34**
Can be rebased and merged if you like, so it'll be in the PR on Andres Github

### CODE REVIEW

**Comment by andi34** [comment]
You might like to also include https://github.com/andi34/photobooth/commit/31e6f7c4db060293433c9b0108b7c416e224190d and https://github.com/andi34/photobooth/commit/c324c932413b1758db993226e392de05f8f2aff1 , at least the first one would also need adjustments for the responsive theme.

**Comment by andi34** [comment]
ok, must be something on my end (maybe the theme change commit). on your branch now with recreated css files, but nothing apears:

Screenshot_2019-09-20_10-07-41

**Comment by sualko** [comment]
What is a cups button?

**Comment by andi34** [comment]
> What is a cups button?

button to open CUPS (an open source printing system used on linux)

Screenshot_2019-09-26_15-40-17

**Pull request closed without merging**
